#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="${COMPOSE_FILE:-$ROOT_DIR/docker-compose.prod.yml}"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env.prod}"
SERVICE_NAME="zeroclaw"
CONTAINER_NAME_DEFAULT="zeroclaw-prod"

PROVIDER_SET=0
MODEL_SET=0
HOST_PORT_SET=0
API_KEY_SET=0
SKIP_SMOKE=0

PROVIDER="${PROVIDER:-openrouter}"
MODEL="${ZEROCLAW_MODEL:-openrouter/auto}"
HOST_PORT="${HOST_PORT:-3000}"
CONTAINER_NAME="${CONTAINER_NAME:-$CONTAINER_NAME_DEFAULT}"
API_KEY_INPUT="${API_KEY:-}"
SMOKE_MESSAGE="${SMOKE_MESSAGE:-Reply with exactly: production smoke passed.}"

usage() {
  cat <<'EOF'
Create and start a local production ZeroClaw container, then verify it.

Usage:
  ./scripts/prod_local_up.sh [options]

Options:
  --api-key <key>         Provider API key (recommended on first run)
  --provider <name>       Provider name (default: openrouter)
  --model <name>          Model name (default: openrouter/auto)
  --host-port <port>      Host port mapped to container 3000 (default: 3000)
  --container <name>      Container name (default: zeroclaw-prod)
  --skip-smoke            Skip pair+webhook LLM smoke test
  --message <text>        Smoke-test message payload
  -h, --help              Show this help

Examples:
  ./scripts/prod_local_up.sh --api-key sk-or-v1-...
  ./scripts/prod_local_up.sh --provider openai --model gpt-4o-mini --api-key sk-...
EOF
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: required command not found: $1" >&2
    exit 1
  fi
}

resolve_key_var() {
  case "$1" in
    openrouter) echo "OPENROUTER_API_KEY" ;;
    openai) echo "OPENAI_API_KEY" ;;
    anthropic) echo "ANTHROPIC_API_KEY" ;;
    *) echo "API_KEY" ;;
  esac
}

while [ $# -gt 0 ]; do
  case "$1" in
    --api-key)
      API_KEY_INPUT="$2"
      API_KEY_SET=1
      shift 2
      ;;
    --provider)
      PROVIDER="$2"
      PROVIDER_SET=1
      shift 2
      ;;
    --model)
      MODEL="$2"
      MODEL_SET=1
      shift 2
      ;;
    --host-port)
      HOST_PORT="$2"
      HOST_PORT_SET=1
      shift 2
      ;;
    --container)
      CONTAINER_NAME="$2"
      shift 2
      ;;
    --skip-smoke)
      SKIP_SMOKE=1
      shift
      ;;
    --message)
      SMOKE_MESSAGE="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

PARSED_PROVIDER="$PROVIDER"
PARSED_MODEL="$MODEL"
PARSED_HOST_PORT="$HOST_PORT"

require_cmd docker
require_cmd curl

if ! docker compose version >/dev/null 2>&1; then
  echo "error: docker compose is required (v2 plugin)" >&2
  exit 1
fi

# Load existing .env.prod as fallback values when present.
if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

if [ "$PROVIDER_SET" -eq 1 ]; then
  PROVIDER="$PARSED_PROVIDER"
else
  PROVIDER="${PROVIDER:-openrouter}"
fi

if [ "$MODEL_SET" -eq 1 ]; then
  MODEL="$PARSED_MODEL"
else
  MODEL="${ZEROCLAW_MODEL:-$MODEL}"
fi

if [ "$HOST_PORT_SET" -eq 1 ]; then
  HOST_PORT="$PARSED_HOST_PORT"
else
  HOST_PORT="${HOST_PORT:-3000}"
fi

KEY_VAR="$(resolve_key_var "$PROVIDER")"
if [ "$API_KEY_SET" -eq 0 ]; then
  KEY_FROM_PROVIDER_VAR="${!KEY_VAR:-}"
  KEY_FROM_GENERIC="${API_KEY:-}"
  if [ -n "$KEY_FROM_PROVIDER_VAR" ]; then
    API_KEY_INPUT="$KEY_FROM_PROVIDER_VAR"
  elif [ -n "$KEY_FROM_GENERIC" ]; then
    API_KEY_INPUT="$KEY_FROM_GENERIC"
  fi
fi

if [ -z "$API_KEY_INPUT" ]; then
  if [ -t 0 ]; then
    read -r -s -p "Enter API key for provider '${PROVIDER}': " API_KEY_INPUT
    echo
  fi
fi

if [ -z "$API_KEY_INPUT" ]; then
  echo "error: missing API key. Pass --api-key or set ${KEY_VAR}/API_KEY in environment." >&2
  exit 1
fi

echo "Writing ${ENV_FILE#$ROOT_DIR/} ..."
cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/prod_local_up.sh
PROVIDER=${PROVIDER}
ZEROCLAW_MODEL=${MODEL}
HOST_PORT=${HOST_PORT}
ZEROCLAW_ALLOW_PUBLIC_BIND=true
API_KEY=${API_KEY_INPUT}
${KEY_VAR}=${API_KEY_INPUT}
EOF
chmod 600 "$ENV_FILE"

echo "Writing ${COMPOSE_FILE#$ROOT_DIR/} ..."
cat >"$COMPOSE_FILE" <<EOF
services:
  ${SERVICE_NAME}:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    image: zeroclaw:prod
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "127.0.0.1:\${HOST_PORT:-3000}:3000"
    volumes:
      - zeroclaw-data:/zeroclaw-data
    command: ["daemon", "--port", "3000", "--host", "[::]"]
    healthcheck:
      test: ["CMD", "zeroclaw", "doctor"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  zeroclaw-data:
EOF

echo "Starting production stack ..."
docker compose -f "$COMPOSE_FILE" up -d --build

HEALTH_URL="http://127.0.0.1:${HOST_PORT}/health"
echo "Waiting for gateway health at ${HEALTH_URL} ..."
for _ in $(seq 1 45); do
  if curl -fsS "$HEALTH_URL" >/dev/null 2>&1; then
    echo "Health check: OK"
    break
  fi
  sleep 2
done

if ! curl -fsS "$HEALTH_URL" >/dev/null 2>&1; then
  echo "error: gateway failed health check at ${HEALTH_URL}" >&2
  echo "hint: inspect logs with: docker logs ${CONTAINER_NAME}" >&2
  exit 1
fi

if [ "$SKIP_SMOKE" -eq 0 ]; then
  echo "Running pair + webhook LLM smoke test ..."
  bash "$ROOT_DIR/dev/gateway_smoke.sh" \
    --host "127.0.0.1" \
    --port "$HOST_PORT" \
    --container "$CONTAINER_NAME" \
    --message "$SMOKE_MESSAGE"
else
  echo "Smoke test skipped (--skip-smoke)."
fi

echo
echo "Production container is up."
echo "Gateway: ${HEALTH_URL}"
echo "Logs: docker logs -f ${CONTAINER_NAME}"
